name: Build and Release on GH
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      GITHUB_SHA:
        description: The SHA of the last tagged commit
        required: true
        type: string
      GITHUB_REF:
        description: Tag ref of the release refs/tags/<tag_name>
        required: true
        type: string

jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    name: Build and Release Cronny on GH
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
      - name: Set env
        run: |
          if [["${{matrix.os}}"="windows"]] then
            echo "{EXT}={.exe}" > >> "$GITHUB_ENV"
          fi
      - name: Build
        run: cargo build --release
      - name: move to correct file
        run: mv target/release/cronny$EXT "cronny-${{matrix.os}}-${{matrix.arch}}$EXT"
      - name: Upload
        run: gh release upload $GITHUB_REF "cronny-${{matrix.os}}-${{matrix.arch}}$EXT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
